### ISSUE TITLE
Sails

### ISSUE THREAD

**Issue by JesusFregoso** [rodrigogs/mysql-events#1]
have you try mysql-events with sails i cant make this work  this is how my mysqlEvents object looks like 

![image](https://user-images.githubusercontent.com/8525045/42651056-7c6e418e-85cb-11e8-83c6-ecbacd54dcdf.png)

and my log file with docker is this 
sudo docker exec dockercontainers_db_1 cat /var/log/mysql/mysql-bin.000002

![image](https://user-images.githubusercontent.com/8525045/42651131-b6ea1c52-85cb-11e8-9fa3-8dcbf41d63dd.png)

**Comment by JesusFregoso** [comment]
the error was the docker container he wasnt writting the logs into the /var/log/mysql/ so i change the docker for mysql running locally and now it works but i have another problem.when i  insert,update or delete into an specific table im getting this error and the event crash: NodeError: The value of "value" is out of range. It must be >= -128 and <= 127. Received -256

**Comment by rodrigogs** [comment]
Can you provide me more details about your docker container configuration?

**Comment by JesusFregoso** [comment]
we already resolve was something wrong with our version of nodejs we
drowngrade from lastest to the stable and fix our problems, thanks by the
way.

Jesus Fregoso
Software Developer, Kichick
Móvil: 6692780477
Dirección: Mazatlan, Sinaloa
Email: jessfregoso0@gmail.com <asarazm@gmail.com>

2018-07-17 22:59 GMT-06:00 Rodrigo Gomes da Silva <notifications@github.com>
:

**Comment by rodrigogs** [comment]
Oh, its nice to know. Thanks for the feedback.
