### ISSUE TITLE
Is there any way to get the raw SQl statement that was executed during an event?

### ISSUE THREAD

**Issue by sam26880** [rodrigogs/mysql-events#10]
I know that there's a new setting available as of MySQL 5.6.2 called binlog_rows_query_log_events which logs the raw SQL to the binlog. 

Is there a way to get that value?

The reason why I need this is because the existing package lets me know that some event occurred. Such as INSERT, UPDATE or DELETE. However, it doesn't tell me what the 'WHERE' condition that was used in cases of UPDATE or DELETE.

It'd be good to get the raw sql in that case to know exactly which query was executed.

**Comment by rodrigogs** [comment]
You're able to catch raw events by using: 
```javascript
new MySQLEvents({ ... })
  .on(MySQLEvents.EVENTS.BINLOG, (event) => {
    doSomething(event);
  });
```

Check if those raw events have the info you're looking for.

**Comment by sam26880** [comment]
I think you misunderstood me. I'm not talking about the raw events. I'm talking about the raw SQL. Does the event have the actual SQL that caused that INSERT, UPDATE or DELETE event?

**Comment by rodrigogs** [comment]
I don't remember, but if it has, it's on the raw binlog events. Sorry, but you'll have to check it :/

**Comment by rodrigogs** [comment]
Is it resolved?
