### ISSUE TITLE
AWS MySql RSD not working

### ISSUE THREAD

**Issue by AviFix** [rodrigogs/mysql-events#33]
Hi

I'm trying to monitor my MySQL rds DB.  I get the log message "Waiting for database vents" bu nothing happens when I change values in the DB tables 

I'm using this example code
`

    const MySQLEvents = require('@rodrigogs/mysql-events');

    const program = async () => {
        const instance = new MySQLEvents({
            host: DB_HOST,
            user: DB_USER,
            password: DB_PASSWORD,
         }, {
             startAtEnd: true,
        });

        await instance.start();

        instance.addTrigger({
            name: 'Whole database instance',
            expression: '*',
            statement: MySQLEvents.STATEMENTS.ALL,
            onEvent: (event) => {
                console.log(event);
            },
        });

         instance.on(MySQLEvents.EVENTS.CONNECTION_ERROR, console.error);
         instance.on(MySQLEvents.EVENTS.ZONGJI_ERROR, console.error);
    };

    program()
        .then(() => console.log('Waiting for database vents...'))
        .catch(console.error);

`

Any ideas?

**Comment by Chonne** [comment]
In your parameter group, is `binlog_format` set to "ROW"?
I think I had the same issue, RDS' default value being "MIXED".

Also, if you use RDS and decide to eventually use the latest binlog position, keep in mind that RDS regularly purges the binlogs, unless you set the binlog retention yourself (not as a mysql config parameter): https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/mysql_rds_set_configuration.html#mysql_rds_set_configuration-usage-notes.binlog-retention-hours

**Comment by AviFix** [comment]
Thanks a lot
That fixed it

**Comment by AltayAkkus** [comment]
> 
> 
> Thanks a lot
> That fixed it

mind closing the issue :smile:
