### ISSUE TITLE
Cannot read property 'COLUMN_NAME' of undefined

### ISSUE THREAD

**Issue by houyanchao** [rodrigogs/mysql-events#4]
After starting the monitoring, I will encounter this error in about half a day, and I have encountered it many times.

![wx20181023-115543](https://user-images.githubusercontent.com/9604104/47334760-96f99400-d6ba-11e8-85bc-e61dee3cfdbf.png)

**Comment by rodrigogs** [comment]
It could happen when your binlog has event data from an already deleted column or schema. We can debug it together if you need to.

**Comment by houyanchao** [comment]
We can debug it together

There is another question，i did not listen to the table ha_health_check and always trigger ZONGJI_ERROR

![image](https://user-images.githubusercontent.com/9604104/47402565-de465a00-d778-11e8-92b9-497df4a46fe3.png)

![image](https://user-images.githubusercontent.com/9604104/47402583-fae29200-d778-11e8-8342-a8c1d50e686d.png)

**Comment by rodrigogs** [comment]
To filter your triggers we have to read every event from the binlogs. So, if there is some inconsistency there, it should throw errors.

**Comment by houyanchao** [comment]
How should we solve the problem of "Cannot read property 'COLUMN_NAME' of undefined"?

**Comment by houyanchao** [comment]
When this error occurs, the listener will stop and it will not be monitored by subsequent changes to the data table. This affects business logic

**Comment by rodrigogs** [comment]
I'll check it as soon as I can. If you find the problem, a PR is also very welcome :)

**Comment by rodrigogs** [comment]
Problem is right here: https://github.com/rodrigogs/zongji/blame/5e313b3947891e404dc3b5dcc8e469efb9ad1997/lib/binlog_event.js#L195

I have no database configured to test it now, and it's 01:00 AM here hahaha

I'll try to have a look at it tomorrow. For sure we will solve this ;)

**Comment by houyanchao** [comment]
Hahahaha, I am here during the day. Thank you very much.

**Comment by rodrigogs** [comment]
Sorry @houyanchao, this issue is here for a long time. I've been quite busy and I don't have time to debug and fix it right now. I'll try to fix this as soon as possible.

**Comment by taieb-tk** [comment]
Is this solved? I seem to have the same problem..
